name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.4, 8.5]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, json
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run static analysis
        run: composer analyse

      - name: Run tests
        run: composer test